# Generated by Django 5.2.4 on 2025-07-20 17:49

from django.db import migrations
from django.utils import timezone


def create_initial_data(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    AccountApplication = apps.get_model('accounts', 'AccountApplication')
    # 建立 demo 使用者（密碼為 'demo'，請用 make_password 產生 hash）
    demo_user, created = User.objects.get_or_create(
        id=1,
        defaults={
            "username": "demo",
            "password": "pbkdf2_sha256$600000$SF0EKQ0O92mxtosw50w7N3$Ta5H9SmcxuLNjpIvcHhDYtYuHgU1rEM09vsGkGINcPs=",
            "is_superuser": False,
            "is_staff": False,
            "is_active": True,
        }
    )
    # 建立預設帳戶申請
    AccountApplication.objects.create(
        account_name='預設帳戶',
        phone='0912345678',
        address='台北市',
        status='PENDING',
        user=demo_user,
        submitted_at=timezone.now(),
        updated_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]